
hooks_enabled = true

[mcp_servers.filesystem]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-filesystem", "./", "/tmp"]


[[hooks]]
name='test_before_tool'
trigger='before_tool'
command='python3 ./scripts/test_tool.py'


[[hooks]]
name='test_after_tool'
trigger='after_tool'
command='python3 ./scripts/test_tool.py'

[[hooks]]
name='test_before_agent'
trigger='before_agent'
command='python3 ./scripts/test_tool.py'